# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a750db1871bcf9f43bae7cf2405d603a5814fbd65c42826afaca8207dfd37ad59d6544235e99ee9637d82d86b1489de5445bb317687379eb82e74927faa831

test:
  secret_key_base: 0c8442311236fd0ec703cf794b9bf112c6af9a72d81f36f161999bb0cb06aab91c045878f2323bdb39f27645aaa51456265bb916f1e5919a08a03e822ad0e780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
